[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solpredict = "DNV6CfgycfyW2C1TgQfqMkWPkr7YmreEKizxFhef3GEC"

[programs.localnet]
solpredict = "DNV6CfgycfyW2C1TgQfqMkWPkr7YmreEKizxFhef3GEC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/solpredict.ts"
