[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solpredict = "HVshSwptqBYKWM9MpZrA1bdP7zQ6RzJXVbr5PUR7wvtr"

[programs.localnet]
solpredict = "HVshSwptqBYKWM9MpZrA1bdP7zQ6RzJXVbr5PUR7wvtr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/solpredict.ts"
