-- Migration 0007: Converge the migration set to app/src/lib/db/schema.ts
--
-- Two columns declared in schema.ts were never created by any migration
-- (0000-0006), so a database built purely from migrations would fail at
-- runtime when the indexer/reducer writes them:
--
--   1. markets_cache.total_volume  (schema.ts line 44) — written by
--      applyTradeEvent (reducer.ts:402) and read by getMarketList sorting /
--      getAllMarkets ordering. 0006 added markets_cache columns but omitted it.
--   2. price_history.outcome_index / price_bps / volume (schema.ts lines 90-93)
--      — 0000 created price_history with legacy columns (yes_pct, yes_pool_sol,
--      no_pool_sol, total_volume); 0003 dropped the first three but never added
--      the new ones; 0006 only added an index. The reducer inserts
--      outcome_index/price_bps/volume (reducer.ts:413-419) and the data layer
--      reads them (data/markets.ts getPriceHistory, db/markets-store.ts
--      getMarketPriceHistory).
--
-- Every statement is idempotent so the migration can be re-run on any state
-- (fresh database, partially-migrated database, or one where these columns
-- already exist via an earlier ad-hoc push).
--
-- Applied against the canonical schema.ts, not generated by drizzle-kit.

-- =============================================================================
-- 1. markets_cache.total_volume
-- =============================================================================
ALTER TABLE "markets_cache" ADD COLUMN IF NOT EXISTS "total_volume" numeric(18, 9) DEFAULT '0';

-- =============================================================================
-- 2. price_history: outcome_index / price_bps / volume
-- =============================================================================
ALTER TABLE "price_history" ADD COLUMN IF NOT EXISTS "outcome_index" integer DEFAULT 0;
ALTER TABLE "price_history" ADD COLUMN IF NOT EXISTS "price_bps" integer;
ALTER TABLE "price_history" ADD COLUMN IF NOT EXISTS "volume" numeric(18, 9);

-- =============================================================================
-- 3. Ensure price_history keeps its market+timestamp index for chart reads
--    (schema.ts declares it; 0006 added it, but make it safe for fresh builds).
-- =============================================================================
CREATE INDEX IF NOT EXISTS "price_history_market_ts_idx" ON "price_history" ("market_pubkey","timestamp");